name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1


    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ~/twplace/twplace-be/;
          git pull;
          docker compose  -f ~/twplace/docker-compose.yaml down -v;
          docker compose  -f ~/twplace/docker-compose.yaml up --build -d;
